require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'spec/factories/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let', 'factory', 'FactoryBot.define']

RSpec/ContextMethod:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 11

RSpec/ExampleLength:
  Max: 25
  
Capybara/FeatureMethods:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/FormatString:
  Enabled: false